SELECT *
FROM (
SELECT SUBSTR(SALES_DATE, 1, 10) AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT FROM ONLINE_SALE
WHERE SALES_DATE LIKE '2022-03%'
UNION
SELECT SUBSTR(SALES_DATE, 1, 10) AS SALES_DATE, PRODUCT_ID, NULL, SALES_AMOUNT FROM OFFLINE_SALE
WHERE SALES_DATE LIKE '2022-03%'
) AS sales_data
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID