SELECT DISTINCT FIRST_HALF.FLAVOR
FROM FIRST_HALF
JOIN ICECREAM_INFO
ON FIRST_HALF.TOTAL_ORDER > 3000
AND ICECREAM_INFO.INGREDIENT_TYPE = 'fruit_based'
AND FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR
ORDER BY FIRST_HALF.TOTAL_ORDER DESC