SELECT CAR_ID, ROUND(SUM(DATEDIFF(END_DATE,START_DATE) + 1) / COUNT(CAR_ID) , 1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING ROUND(SUM(DATEDIFF(END_DATE,START_DATE) + 1) / COUNT(CAR_ID) , 1) >= 7
ORDER BY ROUND(SUM(DATEDIFF(END_DATE,START_DATE) + 1) / COUNT(CAR_ID) , 1) DESC, CAR_ID DESC