SELECT MEMBER_PROFILE.MEMBER_NAME, REST_REVIEW.REVIEW_TEXT, SUBSTR(REST_REVIEW.REVIEW_DATE, 1, 10) AS REVIEW_DATE
FROM REST_REVIEW
JOIN MEMBER_PROFILE
ON REST_REVIEW.MEMBER_ID = (SELECT MEMBER_ID FROM REST_REVIEW GROUP BY MEMBER_ID ORDER BY COUNT(MEMBER_ID) DESC LIMIT 1)
AND REST_REVIEW.MEMBER_ID = MEMBER_PROFILE.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT


# MEMBER_ID가 가장 많이 언급된 MEMBER_ID를 구함
# 해당 MEMBER_ID의 MEMBER_NAME, REVIEW_TEXT, REVIEW_DATE 구함
# REVIEW_DATE를 기준으로 오름차순, REVIEW_TEXT를 기준으로 오름차순