SELECT a.AUTHOR_ID, b.AUTHOR_NAME, a.CATEGORY, SUM(a.PRICE * c.SALES) AS TOTAL_SALES
FROM BOOK AS a
JOIN AUTHOR AS b ON a.AUTHOR_ID = b.AUTHOR_ID
JOIN BOOK_SALES AS c ON a.BOOK_ID = c.BOOK_ID
WHERE c.SALES_DATE LIKE '2022-01%'
GROUP BY a.CATEGORY, a.AUTHOR_ID
ORDER BY a.AUTHOR_ID ASC, CATEGORY DESC