SELECT HISTORY_ID, CAR_ID, SUBSTR(START_DATE,1,10) AS START_DATE, SUBSTR(END_DATE,1,10) AS END_DATE,
IF(DATEDIFF(END_DATE, START_DATE) +1 >= 30, '장기 대여', '단기 대여') AS RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE LIKE '2022-09%'
ORDER BY HISTORY_ID DESC