SELECT a.REST_ID, a.REST_NAME, a.FOOD_TYPE, a.FAVORITES, a.ADDRESS, ROUND(AVG(b.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO AS a
JOIN REST_REVIEW AS b
ON a.REST_ID = b.REST_ID
AND a.ADDRESS LIKE '서울%'
GROUP BY REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS
ORDER BY AVG(b.REVIEW_SCORE) DESC, a.FAVORITES DESC